### PR TITLE
Add dataset containing StoraEnso LVL materials

### LINKED ISSUE #151: Add StoraEnso LVL material dataset
#### Description:

Add dataset containing timber data for corresponding to StoraEnso LVL-S and LVL-X:
image

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #151

 

Add dataset containing LVL-S and LVL-X materials based on Stora Enso material data.

 ### Test files

[Data here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Datasets/%23151-AddLVLMaterials?csf=1&web=1&e=VP7a5c)

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Review by peterjamesnugent — APPROVED** [review]
I have checked all values for LVL-S and LVL-X and happy they match the source data. 

Happy both materials deserialise correctly in the component too.

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by peterjamesnugent** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 23567739654

**Pull request merged**
