### PR TITLE
Created US Data

### LINKED ISSUE #4: BHoM_Datasets: Create US Data

### PR DESCRIPTION
**Pull request by JosefTaylor**
Fixes #4 
Need to check data.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
Added `fixes` keyword to auto close the issue once @enarhi and @IsakNaslundBh are happy and this is merged :smile:

**Comment by IsakNaslundBh** [comment]
Link to my testscript for comparing BHoM values and serialised values here:

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Datasets/Cathalogue%20vs%20BHoM%20test?csf=1&e=cDOv0J

**Comment by IsakNaslundBh** [comment]
Also looks to be a few duplicates of the W4X13 section in the data.

**Comment by JosefTaylor** [comment]
Alright @IsakNaslundBh and @enarhi, that should take care of those issues.

**Comment by IsakNaslundBh** [comment]
Thanks @JosefTaylor .

Would you be able to get one of your colleagues in US to verify the content of the Data? I know @enarhi is on leave and would be good to get this checked by an american engineer!

**Comment by dlamianski** [comment]
Spot checked and approved implemented sections.

**Comment by JosefTaylor** [comment]
@IsakNaslundBh are we ready?

**Pull request merged**
