### PR TITLE
Add eu steel section properties

### LINKED ISSUE #6: BHoM_Datasets: Create EU steel profile dataset
Create EU version of the profile datasets that exist for UK and US

### PR DESCRIPTION
**Pull request by MartinHenriksen**
Added common EU section profiles sourced from manufacturers sites (Arcelormittal Orange Book and Tata Steel Blue Book).
Datasets added:
CHS, RHS, SHS, IPE, HE, UPE, UPN, L-equal and L-unequal

 ### Issues addressed by this PR

 Closes #6 

 

 ### Test files

to test copy the "EU_SteelSections" folder into `C:\ProgramData\BHoM\Datasets\SectionProperties`

 ### Changelog

- 'Added EU section properties to Datasets'

 ### Additional comments

Warping constants for channel sections in the Orange Book have been miscalculated (overly conservative) - the authors have been notified

### CODE REVIEW

**Comment by rwemay** [comment]
These are at the top level `Datasets/SectionProperties`. @IsakNaslundBh , we talked previously about organising these to better match/reflect namespaces, so more like `Datasets/Structure/SectionProperties`. Don't know if we want to merge more into the top level before shifting all of these?

**Comment by IsakNaslundBh** [comment]
> New EU profiles are not shown in the dropdown in CreateData node. They appear to be nested one level higher than UK sections, because they are achievable using Explode.

@MartinHenriksen , for this, make sure you have only a single Dataset in each of the JSON files. The FIle adapter might be adding rather than replacing if you have been pushing multiple times to the same file!

> These are at the top level Datasets/SectionProperties. @IsakNaslundBh , we talked previously about organising these to better match/reflect namespaces, so more like Datasets/Structure/SectionProperties. Don't know if we want to merge more into the top level before shifting all of these?

@rwemay this has been asked for for quite some time, and given we will need to put a versioning system in place etc anyways to handle the UK and US sections, it will not be that big of a difference to take care of EU sections as well.
Given that this will significantly help the EU guys, I prefer to get this in without being blocked off at this stage.

**Comment by MartinHenriksen** [comment]
@IsakNaslundBh that is exactly what was happening - maintenance script updated to delete before writing to prevent this.

**Review by arturtomczak — APPROVED** [review]
thank you @MartinHenriksen, dataset approved.

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Had a review of this as well, comparing the tabulated results to the results of the engine calculations.

First, would not add in the UPNs at this stage, as that profile is not yet supported. Would need to add tapered flange channel profiles before getting those in. (currently 10+% diffing between the profile and the section constants)

Secondly, the a lot of the angles seem to be diffing between tabulated values and calculated values, sometimes with differences > 10%. A lot of this seem to be related to the torsional constant, which ofc is a bit more tricky to calculate, but also other properties such as elastic modulus shows differences of up to 5%. Wonder if this has to do with errors in the tables, as for example the profile here:
image

Can not be constructed (the toe radius is larger than the plate thickness). Martin have you made any adjustments here?

Then, some of the Welz values for the smaller IPEs are a bit off as well. THink the values are agreeing with the tables, but looking at the tables, it seem as they have just rounded the values to 0 decimals rather than to 3 significant figures:

image

Wonder if we are better off using our calculated values for this case, as rounding to a single figure sounds a bit daft to me..

The, sources needs to be update, especially the source links as all of them are pointing to the same two tables:

image

I have put up a testscript here https://burohappold.sharepoint.com/:f:/s/BHoM/ElASxL4-OxdLsL6WFesTfX0BpR3XCG4BbD7Xp3GWAL9Jgg?e=qehs2u

**Review by staintono — CHANGES_REQUESTED** [review]
The Avz values for I & H Sections are not correctly calculated.
MicrosoftTeams-image (5)
MicrosoftTeams-image (6)
They have been calculated using hw*tw, however this can be increased using the following formula
MicrosoftTeams-image (7)
The rest of the values are correct

**Comment by MartinHenriksen** [comment]
@staintono while the calculation method you reference might be more accurate, the more conservative calculation method is what we are using in UK and US sections. This is also what is used in Both Robot and RFEM so I think the conservative value is more in line with what the user will expect.
RFEM:
image
Robot:
image

**Review by staintono — APPROVED** [review]
looks all good

**Pull request merged**
