### PR TITLE
Add embodied carbon to materials

### LINKED ISSUE #12: BHoM_Datasets: Add embodied carbon to US datasets

### PR DESCRIPTION
**Pull request by JosefTaylor**
### NOTE: Depends on 
Adapting to [BHoM PR 560](https://github.com/BHoM/BHoM/pull/560)

   
### Issues addressed by this PR

Closes #12

Re-serialized US sections and materials with embodied carbon

### CODE REVIEW

**Comment by JosefTaylor** [comment]
@enarhi Can you check this?

**Comment by JosefTaylor** [comment]
@FraserGreenroyd is this PR title good enough for ya?

**Comment by JosefTaylor** [comment]
@IsakNaslundBh feel free to merge when you get to it

**Comment by JosefTaylor** [comment]
@enarhi @IsakNaslundBh I fixed the issue with the missing HSS, number of sections is now correct.

**Comment by JosefTaylor** [comment]
Scratch that, I serialized without the carbon. Will fix this afternoon.

**Comment by JosefTaylor** [comment]
All's well. @IsakNaslundBh @FraserGreenroyd @enarhi review and merge when ready!

**Comment by FraserGreenroyd** [comment]
@enarhi the deadline for including this PR in the 3.0 beta installer is 2pm UTC Thursday 19th December 2019, will you be able to review before then or can you/ @JosefTaylor ask someone else to take a look? As this is US based data we're keen to ensure a US based engineer takes a review before we merge :smile:

**Comment by enarhi** [comment]
Could have sworn I had already approved, as I had already reviewed a few days ago with the new changes! LGTM!

**Comment by al-fisher** [comment]
Ah! Thanks @enarhi! 👍

**Pull request merged**
