### PR TITLE
Updated Glazing and FrameEdge Datasets with Material Names and Fixed U-values

### LINKED ISSUE #126: Updates to Facade Datasets - GlazingConstructions and FrameEdgeProperties
#### Description:
Make the following updates to the Facade datasets:

GlazingConstructions
- Add material names to glazing materials pulled from EnergyPlus dataset
- Add new dataset objects for double IGUs with e-0.05, low-e coating

FrameEdgeProperties
- Fix U-values for operable frame edge types

### PR DESCRIPTION
**Pull request by vgreen-BH**
### Issues addressed by this PR

 Closes #126 

Updates to FrameEdgeProperties and GlazingConstruction datasets. Removed superseded datasets.

FrameEdgeProperties
- Fixed U-values for operable/fixed window types

GlazingConstructions
- Added material names for glazing materials
- Added new IGU types for double IGUs with e-0.05 coating

 ### Test Files

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=HlvYHp&cid=ab402372%2D7702%2D48ef%2Db6bc%2D9c3f66547c0a&RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FBHoM%5FDatasets%2FFacade%20Datasets&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4

### CODE REVIEW

**Review by enarhi — APPROVED** [review]
LGTM, tested both datasets and confirmed presence of new material names as well as updated U values, U Values appear correct and new material names are as expected per the glazing constructions.

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check dataset-compliance

**Pull request merged**
