### PR TITLE
Changed US Steel Section names to match AISC Book

### LINKED ISSUE #65: Use AISC Manual Labels for US Steel SectionProperties

### PR DESCRIPTION
**Pull request by JosefTaylor**
Also changed properties to US Customary units, converted to SI with localisation tools.

 ### NOTE: Depends on 

 ### Issues addressed by this PR

 Closes #65 

 
Set US Steel section names to AISC Manual values, which hopefully should improve library matching from Revit.
Set properties from US Customary units, converted to SI using localisation toolkit, rather than getting metric quantities from the AISC spreadsheet, which were rounded slightly different to the customary quantities.

 ### Test files

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
This seem to no longer be in a Dataset class, which means no source information. good to not loose that.

Also, if you update the names, all old dropdown components will fail.

I will, as soon as I find any time, implement a versioning system for the libraries FYI that I hope can help mitigate that, but if this is needed ASAP, might not be able to wait.

**Comment by maryannewachter** [comment]
Fixed source information as requested by @IsakNaslundBh. However, AISC lacks consistency in naming Pipe and Round HSS sections (Manual will say HSS4x0.500, but the database will say HSS4.000x0.500). Suggest that we map similar names to the same existing section somehow.

**Comment by JosefTaylor** [comment]
This looks good to me. Sources and names are correct, values align exactly to the values in the spreadsheet. 

Testing the properties against calculated values shows shear areas are not in line with the default BHoM calculation, but these are in line with formulas shown in the design for shear section (G) of the steel manual.

**Review by maryannewachter — APPROVED** [review]

**Review by jean-lucjacksonBH — APPROVED** [review]

**Comment by JosefTaylor** [comment]
@IsakNaslundBh mind merging this?

**Pull request merged**
