### PR TITLE
Add metal deck datasets

### LINKED ISSUE #152: Add MetalDeck datasets
#### Description:

Should add information for different MetalDecks from different manufacturers. For example:

https://smdltd.co.uk/products-services/floor-deck/tr60/

and 

https://www.richardlees.co.uk/pages/ribdeck-e60.php

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

 Closes #152

 

Add dataset for RichardLees decking Corrugated deck datasets
Add dataset for SMD corrugated deck datasets

 ### Test files

[Data found here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Datasets/%23151-Decking?csf=1&web=1&e=yGYp3u)

 ### Changelog

 ### Additional comments

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check project-compliance

**Review by peterjamesnugent — COMMENTED** [review]
RF51 appears to have a depth of 51mm in [SMD.BRO.121.V4-SMD-TAB-Deckmanual](https://burohappold.sharepoint.com/:b:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Datasets/%23151-Decking/SMD.BRO.121.V4-SMD-TAB-Deckmanual.pdf?csf=1&web=1&e=bkdVqe,) but 52mm everywhere else I can find it:
image

How did you calculate the top width for the Ribdeck S60 and 80 products?

**Comment by IsakNaslundBh** [comment]
> RF51 appears to have a depth of 51mm in [SMD.BRO.121.V4-SMD-TAB-Deckmanual](https://burohappold.sharepoint.com/:b:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Datasets/%23151-Decking/SMD.BRO.121.V4-SMD-TAB-Deckmanual.pdf?csf=1&web=1&e=bkdVqe,) but 52mm everywhere else I can find it: image
> 
> How did you calculate the top width for the Ribdeck S60 and 80 products?

Good catches @peterjamesnugent . AS discussed offline, I have updated height to 51 for the R51 SMD deck.

For the RLD S60 and 80 products I have opted to simply remove them for now until an official good source of exact dimensions can be found.

**Review by peterjamesnugent — APPROVED** [review]
Happy the RLD dataset deserialises correctly now and the S60/S80 decks have been removed.

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 23660791901

**Pull request merged**
