### PR TITLE
Creation of IBC Occupancy + ASHRAE Vent area and People Rates Datasets

### PR DESCRIPTION
**Pull request by michaelhoehn**
### Issues addressed by this PR
Addresses issue #15 

### Test files

IBC ASHRAE comparison

### Additional comments

Add SpacePlanning datasets are proposed to be aid in space planning and space type calculations. Examples being; MEP - plumbing fixture counts per occupancy classification; Structures - Live load assumptions based on space type categorisation

### CODE REVIEW

**Comment by rwemay** [comment]
Looking good! Great to see the occupancy data getting tidied up. Are we removing the old/existing IBC/other occupancy data at the same time so there's no duplication? 

Is folder naming/location specific enough? I'd started putting in a specific 'Occupancy' folder, knowing there will likely be a LOT of codes/dataset. 

On source, Is this the latest approach? I thought we were heading toward a Dataset object, that then contains a source object alongside the individual objects (as opposed to printing the source as a single string on every data item). @IsakNaslundBh  can comment on how close to implemented that is.

**Comment by IsakNaslundBh** [comment]
@rwemay The Dataset object is still in an open PR here https://github.com/BHoM/BHoM/pull/582 . That will need to get closed out first, once that is done I need to do some work on the Library_Engine to make it work as intended with the Dataset. Once all that is done, the approach going forward will be as you stated. One Dataset object in each Dataset file, containing source information as well as the data (which will be exactly the same as it is now).

Will have a grace periods of a few month where the current approach will be supported as well, but long term all Dataset will need to be wrapped in a Dataset object.

As for this PR, think it is fine for it to get merged as is (given tested/approved by appropriate people ofc) if @michaelhoehn is fine knowing he will need to re-create it at some point in the future into the new format.

**Comment by michaelhoehn** [comment]
Addition of ASCE 7 2002 Occupancy per Live Load Dataset. 

ASCE72002

**Comment by kayleighhoude** [comment]
@rwemay to address the comment about breaking this down into further folders, we only have one for occupancy at the moment (ASHRAE technically gives you occupancy as well, but is intended for internal gains, same with ASCE) may keep this in Space Planning for the time being then breakout in the future. open to ideas though :)

**Comment by rwemay** [comment]
Ok, maybe worth a quick chat on this tomorrow - looks like we're merging structural loads with occupancy within a space planning data set(?) Also adding multiple unit outputs with a new property naming convention? Would the unit conversion not be dealt with in units/localisation engines?

**Comment by FraserGreenroyd** [comment]
@michaelhoehn can you confirm the state of this PR and associated datasets please? I'm imagining this is stale and could be closed in favour of a new PR following the new datasets knowledge of the last couple weeks? :smile:

**Comment by michaelhoehn** [comment]
Closing this PR. Datasets to be recreated as needed utilising the Dataset Object and proper BHoM objects instead of CustomData objects.

**Pull request closed without merging**
