### PR TITLE
Align dataset folder with namespace

### LINKED ISSUE #121: Reorganise internal folder structure of Datasets folder
#### Broken rules:

The organisation of the Datasets folder needs restructuring to aid discoverability and further growth.

https://github.com/BHoM/BHoM_Datasets/tree/main/DataSets

#### Suggestions to restore compliance:

Would suggest we align folder structure directly with the namespace of the serialised objects

See couple of examples below:
image
image

Requires close out of https://github.com/BHoM/BHoM_Engine/issues/1864 as prerequisite

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### NOTE: Depends on 

Does not depend on to compile, but should not be merged before
https://github.com/BHoM/BHoM_Engine/pull/2845

 ### Issues addressed by this PR

 Closes #121 

 

Update Dataset folder to match namespace for Structures and Graphics

 ### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/ElZxIn8tk9hEmFlsGsYwfxsBDQj3Q6jEijbald347pTANg?e=2geUir

Note 1 to test this, the C:\ProgramData\BHoM\Datasets folder needs to be cleared of any current instances of the files being migrated, as without doing so, the files on main will still exist and be picked up.

Note 2, you will need to build versioning toolkit _after_ you have compiled this to ensure that the Upgraders are copied across to the UpgradesFile. 

 ### Changelog

 ### Additional comments

Putting this on a separate branch name intentionally, as the versioning should be able to be merged without this PR being merged at the same time. This is raised now, before the versioning is merged, to enable simpler testing.

@peterjamesnugent @JosefTaylor putting you as reviewers as a bit of FYI that this might be happening.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
Would not merge this PR until after the release of BHoM 5.2 beta. Best merged early in 5.3. Before merging, the code should be evaluated to find any places where the library engine is called, referencing any of the datasets in here and appropriate updates made to ensure the same data is still received.

**Comment by FraserGreenroyd** [comment]
@JosefTaylor would you have any capacity to review this so we can merge before the beta? 😄

**Review by JosefTaylor — APPROVED** [review]
After following the directions, versioning works great!

**Comment by JosefTaylor** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
thanks @JosefTaylor .

As discussed offline, will aim to get this merged early next milestone, rather than in this one.

Will also require the Versioning json file to get its name updated to 6.0.

**Comment by FraserGreenroyd** [comment]
@IsakNaslundBh any update on this?

**Review by peterjamesnugent — DISMISSED** [review]
Tested with script and no issues.

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by peterjamesnugent — APPROVED** [review]
Approved based on previous review and final commit (compliance change).

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check project-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
