### PR TITLE
Update Mullion Database Materials

### LINKED ISSUE #98: Fix Mullion Dataset Materials for THERM Processing
#### Description:

A minor material naming issue on two mullions in the dataset is preventing them from being able to be converted to THERM geometry.
- Kawneer 2500 PG, 1" to 1/4" Infill, 6" Mullion - Top
- Kawneer 2500 PG, 1" to 1/4" Infill, 6" Mullion - Bottom

### PR DESCRIPTION
**Pull request by vgreen-BH**
### Issues addressed by this PR

 Closes #98 

 
Fixes material naming issues for Kawneer 2500 mullions. 

 ### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Datasets/Facade%20Datasets?csf=1&web=1&e=HlvYHp

### CODE REVIEW

**Review by FraserGreenroyd — COMMENTED** [review]
Given the folder structure provides the drop down options for selecting datasets, could we look at setting the folder structure to be a little bit more specific/better than just straight in at `FrameEdgeProperties`? Happy for it to be a new issue and handled in the next milestone, but one that'd be good to look at @enarhi @vgreen-BH

**Review by enarhi — APPROVED** [review]
LGTM

**Comment by enarhi** [comment]
@FraserGreenroyd agreed, will create a separate issue for that.

**Comment by enarhi** [comment]
@BHoMBot check dataset-compliance

**Pull request merged**
